name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 225000673436.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 225000673436.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: hello-world-nodejs
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::225000673436:role/IaC-Role
          aws-region: us-east-1

      - name: Deploy to ECS
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
